# parent image
FROM stereolabs/zed:3.7-devel-jetson-jp4.3 AS collector
LABEL maintainer="lager_gcs@outlook.com"
LABEL description="Automatically package gust for the jetson nano."

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive
ARG USER_UID=1000
ARG USER_GID=1000

# copy in custom repos
WORKDIR /gust
COPY ./build_scripts ./build_scripts
COPY ./gust_packages ./gust_pagkages
COPY ./src ./src
COPY ./utilities ./utilities

WORKDIR /gust/repos
COPY ./repos/fbs ./fbs
COPY ./repos/lager_sensors ./lager_sensors

# install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      software-properties-common \
      libz-dev \
      qt5-default \
      cmake \
      ruby \
      ruby-dev \
      rubygems \
      build-essential \
    && gem install --no-ri --no-rdoc fpm \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends python3-dev \
    && python3 -m pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*


FROM collector AS builder

WORKDIR /gust

RUN python3 -m pip install ./repos/fbs \
    && python3 -m pip install pyqt5

RUN python3 -m pip install ./repos/lager_sensors/hw_utils && \
    python3 -m pip install ./repos/lager_sensors/radio_receiver && \
    python3 -m pip install ./repos/lager_sensors/zed

# install gust and its dependencies
RUN python3 -m pip install ./src/main/python[linux]

RUN echo "#!/bin/bash" > entrypoint.bash \
    && echo "cd /gust/build_scripts" >> entrypoint.bash \
#    && echo "./release_gust.bash -d" >> entrypoint.bash \
    && chmod +x entrypoint.bash


FROM builder AS runner

WORKDIR /gust

ENTRYPOINT "/gust/entrypoint.bash"
#RUN cd build_scripts  \
#    && ./release_gust.bash -d
