FROM ubuntu:jammy
LABEL maintainer="lager_gcs@outlook.com"
LABEL description="Clone lager sensors repo."
WORKDIR /

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      git \
      openssh-client \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p -m 0600 ~/.ssh \
    && ssh-keyscan -H github.com >> ~/.ssh/known_hosts


RUN --mount=type=ssh git clone git@github.com:drjdlarson/lager_sensors.git