# parent image
FROM stereolabs/zed:3.7-devel-jetson-jp4.3
LABEL maintainer="lager_gcs@outlook.com"
LABEL description="Automatically package gust for the jetson nano."

SHELL ["/bin/bash", "-c"]

# working directory
WORKDIR /app

# install correct version of python and set is as default for python3
RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common git libz-dev qt5-default cmake && \
    git clone https://github.com/ryan4984/fbs.git && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3-dev && \
#   apt-get install -y --no-install-recommends python3-venv && \
#    apt-get install -y --no-install-recommends python3.7 python3.7-dev python3.7-venv && \
#    python3 -m venv "env" && \
#    source env/bin/activate && \
    pip3 install --upgrade pip && \
    pip3 install ./fbs && \
    pip3 install pyqt5 && \
    rm -rf /var/lib/apt/lists/*


# setup in house dependencies
COPY lager_sensors lager_sensors

RUN pip3 install lager_sensors/hw_utils && \
    pip3 install lager_sensors/radio_receiver && \
    pip3 install lager_sensors/zed

# copy the code into the workdir
COPY ./build_*.sh ./
COPY ./after_install.sh ./
COPY ./release_gust.sh ./
COPY gust_packages gust_packages/
COPY src src/

# install gust and its dependencies
RUN pip3 install ./src/main/python[linux]

ENTRYPOINT ["release_gust.sh"]