# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/workspaces/gust/src/main/python/gust/gui/ui/conn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 260)
        MainWindow.setMinimumSize(QtCore.QSize(340, 190))
        MainWindow.setMaximumSize(QtCore.QSize(540, 260))
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label_conn_type = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_conn_type.setFont(font)
        self.label_conn_type.setObjectName("label_conn_type")
        self.gridLayout.addWidget(self.label_conn_type, 0, 0, 1, 1)
        self.comboBox_conn_type = QtWidgets.QComboBox(MainWindow)
        self.comboBox_conn_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_conn_type.setObjectName("comboBox_conn_type")
        self.gridLayout.addWidget(self.comboBox_conn_type, 0, 1, 1, 1)
        self.label_nameinput = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_nameinput.setFont(font)
        self.label_nameinput.setObjectName("label_nameinput")
        self.gridLayout.addWidget(self.label_nameinput, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_nameinput = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_nameinput.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_nameinput.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_nameinput.setText("")
        self.lineEdit_nameinput.setObjectName("lineEdit_nameinput")
        self.horizontalLayout_2.addWidget(self.lineEdit_nameinput)
        self.comboBox_sil_name = QtWidgets.QComboBox(MainWindow)
        self.comboBox_sil_name.setObjectName("comboBox_sil_name")
        self.horizontalLayout_2.addWidget(self.comboBox_sil_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_port = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 2, 0, 1, 1)
        self.comboBox_port = QtWidgets.QComboBox(MainWindow)
        self.comboBox_port.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_port.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_port.setObjectName("comboBox_port")
        self.gridLayout.addWidget(self.comboBox_port, 2, 1, 1, 1)
        self.label_baud = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_baud.setFont(font)
        self.label_baud.setObjectName("label_baud")
        self.gridLayout.addWidget(self.label_baud, 3, 0, 1, 1)
        self.comboBox_baud = QtWidgets.QComboBox(MainWindow)
        self.comboBox_baud.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.gridLayout.addWidget(self.comboBox_baud, 3, 1, 1, 1)
        self.label_color = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_color.setFont(font)
        self.label_color.setObjectName("label_color")
        self.gridLayout.addWidget(self.label_color, 4, 0, 1, 1)
        self.comboBox_color = QtWidgets.QComboBox(MainWindow)
        self.comboBox_color.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_color.setObjectName("comboBox_color")
        self.gridLayout.addWidget(self.comboBox_color, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_connect = QtWidgets.QPushButton(MainWindow)
        self.pushButton_connect.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout.addWidget(self.pushButton_connect)
        self.pushButton_cancel = QtWidgets.QPushButton(MainWindow)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_conn_type.setText(_translate("MainWindow", "CONN TYPE"))
        self.label_nameinput.setText(_translate("MainWindow", "Enter Vehicle\'s Name"))
        self.label_port.setText(_translate("MainWindow", "PORT"))
        self.label_baud.setText(_translate("MainWindow", "BAUD"))
        self.label_color.setText(_translate("MainWindow", "COLOR ID"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
