# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/main/python/gust/gui/ui/conn.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 260)
        MainWindow.setMinimumSize(QtCore.QSize(340, 190))
        MainWindow.setMaximumSize(QtCore.QSize(540, 260))
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"color: rgb(0, 0, 0);")
        self.formLayout = QtWidgets.QFormLayout(MainWindow)
        self.formLayout.setObjectName("formLayout")
        self.label_nameinput = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_nameinput.setFont(font)
        self.label_nameinput.setObjectName("label_nameinput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nameinput)
        self.lineEdit_nameinput = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_nameinput.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineEdit_nameinput.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.lineEdit_nameinput.setText("")
        self.lineEdit_nameinput.setObjectName("lineEdit_nameinput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_nameinput)
        self.label_conn_type = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_conn_type.setFont(font)
        self.label_conn_type.setObjectName("label_conn_type")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_conn_type)
        self.comboBox_conn_type = QtWidgets.QComboBox(MainWindow)
        self.comboBox_conn_type.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_conn_type.setObjectName("comboBox_conn_type")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_conn_type)
        self.label_port = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_port.setFont(font)
        self.label_port.setObjectName("label_port")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_port)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboBox_port = QtWidgets.QComboBox(MainWindow)
        self.comboBox_port.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_port.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_port.setObjectName("comboBox_port")
        self.horizontalLayout_3.addWidget(self.comboBox_port)
        self.lineEdit_extra_tcp = QtWidgets.QLineEdit(MainWindow)
        self.lineEdit_extra_tcp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_extra_tcp.setObjectName("lineEdit_extra_tcp")
        self.horizontalLayout_3.addWidget(self.lineEdit_extra_tcp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_baud = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_baud.setFont(font)
        self.label_baud.setObjectName("label_baud")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_baud)
        self.comboBox_baud = QtWidgets.QComboBox(MainWindow)
        self.comboBox_baud.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_baud.setObjectName("comboBox_baud")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_baud)
        self.label_color = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_color.setFont(font)
        self.label_color.setObjectName("label_color")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_color)
        self.comboBox_color = QtWidgets.QComboBox(MainWindow)
        self.comboBox_color.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_color.setObjectName("comboBox_color")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_color)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_connect = QtWidgets.QPushButton(MainWindow)
        self.pushButton_connect.setStyleSheet("background-color: rgb(138, 226, 52);")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout.addWidget(self.pushButton_connect)
        self.pushButton_cancel = QtWidgets.QPushButton(MainWindow)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_nameinput.setText(_translate("MainWindow", "Enter Vehicle\'s Name"))
        self.label_conn_type.setText(_translate("MainWindow", "CONN TYPE"))
        self.label_port.setText(_translate("MainWindow", "PORT"))
        self.lineEdit_extra_tcp.setText(_translate("MainWindow", "TCP conn."))
        self.label_baud.setText(_translate("MainWindow", "BAUD"))
        self.label_color.setText(_translate("MainWindow", "COLOR ID"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.pushButton_cancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
