# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/workspaces/gust/src/main/python/gust/gui/ui/generic_channels.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 438)
        MainWindow.setStyleSheet("background-color: rgb(203, 230, 255);\n"
"font: 11pt \"Ubuntu Mono\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_heading.setFont(font)
        self.label_heading.setAccessibleDescription("")
        self.label_heading.setStyleSheet("font: 75 16pt \"Ubuntu Mono\";")
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout_4.addWidget(self.label_heading)
        self.verticalWidget_common = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_common.setMinimumSize(QtCore.QSize(230, 60))
        self.verticalWidget_common.setObjectName("verticalWidget_common")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget_common)
        self.verticalLayout.setContentsMargins(25, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4.addWidget(self.verticalWidget_common)
        self.gridLayout_chan = QtWidgets.QGridLayout()
        self.gridLayout_chan.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_chan.setObjectName("gridLayout_chan")
        self.verticalLayout_4.addLayout(self.gridLayout_chan)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_heading.setText(_translate("MainWindow", "HEADING"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
