# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/workspaces/gust/src/main/python/gust/gui/ui/sensors.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SensorsWindow(object):
    def setupUi(self, SensorsWindow):
        SensorsWindow.setObjectName("SensorsWindow")
        SensorsWindow.resize(186, 250)
        SensorsWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QtWidgets.QWidget(SensorsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.pushButton_zed = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zed.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_zed.setFlat(False)
        self.pushButton_zed.setObjectName("pushButton_zed")
        self.gridLayout_2.addWidget(self.pushButton_zed, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        SensorsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SensorsWindow)
        QtCore.QMetaObject.connectSlotsByName(SensorsWindow)

    def retranslateUi(self, SensorsWindow):
        _translate = QtCore.QCoreApplication.translate
        SensorsWindow.setWindowTitle(_translate("SensorsWindow", "Sensors"))
        self.pushButton_zed.setText(_translate("SensorsWindow", "ZED"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SensorsWindow = QtWidgets.QMainWindow()
    ui = Ui_SensorsWindow()
    ui.setupUi(SensorsWindow)
    SensorsWindow.show()
    sys.exit(app.exec_())
